//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RasmiOnline.Business.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BusinessMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BusinessMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RasmiOnline.Business.Properties.BusinessMessage", typeof(BusinessMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یکی از کاربران رسمی آنلاین با نام ‘NAME&apos; مدرکی را به شرح زیر در سایت بارگذاری کرده است  :
        ///شماره سفارش : {0}
        ///وضعیت سفارش : {1}
        ///نوع مدرک : {2}
        ///ساعت تغییر وضعیت : {3}
        ///#آپلود_مدارک.
        /// </summary>
        public static string Attachment_Add {
            get {
                return ResourceManager.GetString("Attachment_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر NAME  ، سفارش به شماره {0} را در تاریخ {1}  لغو کرد . 
        ///#لغو_سفارش.
        /// </summary>
        public static string Cancel_Order {
            get {
                return ResourceManager.GetString("Cancel_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان افزودن نقش جدید به دلیل داشتن نقش فعال وجود ندارد.
        /// </summary>
        public static string CanNotAddNewRoleDueToActiveRole {
            get {
                return ResourceManager.GetString("CanNotAddNewRoleDueToActiveRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یکی از کاربران رسمی آنلاین با نام ‘NAME&apos; وضعیت سفارش را به شرح زیر تغییرداده است :
        ///شماره سفارش : {0}
        ///وضعیت سفارش : {1}
        ///ساعت تغییر وضعیت : {2}
        ///#تغییر_وضعیت.
        /// </summary>
        public static string Change_OrderState_Bot {
            get {
                return ResourceManager.GetString("Change_OrderState_Bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد تخفیف مورد نظر منقضی شده است.
        /// </summary>
        public static string DiscountBeenExpired {
            get {
                return ResourceManager.GetString("DiscountBeenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد تخفیف مورد نظر استفاده شده است.
        /// </summary>
        public static string DiscountBeenUsed {
            get {
                return ResourceManager.GetString("DiscountBeenUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ استفاده از کد تخفیف فرا نرسیده است.
        /// </summary>
        public static string DiscountUseDateNotArrived {
            get {
                return ResourceManager.GetString("DiscountUseDateNotArrived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این رکورد قبلا ثبت شده است.
        /// </summary>
        public static string DuplicateRecord {
            get {
                return ResourceManager.GetString("DuplicateRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات با خطا مواجه شد، دوباره سعی نمایید.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متاسفانه عملیات مورد نظر با خطا مواجه شده است، لطفا مجددا تلاش نمایید.
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی اکانت شما غیر فعال می باشد، برای اطلاعات بیشتر با پشتیبانی تماس بگیرید.
        /// </summary>
        public static string InActiveUser {
            get {
                return ResourceManager.GetString("InActiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد درخواست ایجاد کد تخفیف صحیح نمی باشد.
        /// </summary>
        public static string InvalidCodeCount {
            get {
                return ResourceManager.GetString("InvalidCodeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد تخفیف وارد شده معتبر نیست.
        /// </summary>
        public static string InvalidDiscountCode {
            get {
                return ResourceManager.GetString("InvalidDiscountCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان آپلود فایلی با پسوند {0} وجود ندارد.
        /// </summary>
        public static string InvalidFileExt {
            get {
                return ResourceManager.GetString("InvalidFileExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات وارد شده معتبر نمی باشد.
        /// </summary>
        public static string InvalidInputModelData {
            get {
                return ResourceManager.GetString("InvalidInputModelData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش وارد انتخاب شده معتبر نمی باشد.
        /// </summary>
        public static string InvalidRole {
            get {
                return ResourceManager.GetString("InvalidRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل قبلا ثبت شده است.
        /// </summary>
        public static string MobileNumberIsAlreadyRegistered {
            get {
                return ResourceManager.GetString("MobileNumberIsAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جدید.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه ثبت دفتری.
        /// </summary>
        public static string OfficialCost {
            get {
                return ResourceManager.GetString("OfficialCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای هر سفارش تنها یکبار امکان استفاده از کد تخفیف وجود دارد.
        /// </summary>
        public static string OneDiscountCanBeUsedPerOrder {
            get {
                return ResourceManager.GetString("OneDiscountCanBeUsedPerOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یکی از کاربران رسمی آنلاین با نام  ‘NAME’ یک سفارش با مشخصات زیر را ثبت کرده است:
        ///شماره سفارش : {0}
        ///عنوان سفارش : {1}
        ///زبان سفارش : {2}
        ///ساعت درخواست:  {3}
        ///#ثبت_سفارش.
        /// </summary>
        public static string Order_Add_Bot {
            get {
                return ResourceManager.GetString("Order_Add_Bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME عزیز، سفارش شماره {0} با موفقیت ثبت گردید. به زودی همکاران ما برای پیگیری با شما تماس خواهند گرفت.
        ///www.rasmionline.com.
        /// </summary>
        public static string Order_Add_Sms {
            get {
                return ResourceManager.GetString("Order_Add_Sms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME عزیز، سفارش به شماره {0} در پنل کاربری شما قرار گرفت ، جهت پیگیری سفارش فوق لطفا به پنل کاربری خود مراجعه نمایید .
        ///www.RasmiOnline.com.
        /// </summary>
        public static string Order_Moved_Office {
            get {
                return ResourceManager.GetString("Order_Moved_Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME عزیز، سفارش شماره {0} شما در وضعیت تسویه نهایی قرار گرفته است. لطفا به پنل کاربری خود مراجعه نمایید.
        ///http://panel.rasmiOnline.com.
        /// </summary>
        public static string Pay_All_Factor_Sms {
            get {
                return ResourceManager.GetString("Pay_All_Factor_Sms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا تاریخ را به صورت صحیح وارد نمائید.
        /// </summary>
        public static string PleaseEnterACorrectDateTimeRange {
            get {
                return ResourceManager.GetString("PleaseEnterACorrectDateTimeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ رکوردی برای نمایش یافت نشد.
        /// </summary>
        public static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات با موفقیت انجام شد.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل تعداد کاراکتر 8 است.
        /// </summary>
        public static string TheMinimumNumberOfCharactersIs8 {
            get {
                return ResourceManager.GetString("TheMinimumNumberOfCharactersIs8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یکی از کاربران رسمی آنلاین با نام ‘{0}’ پرداختی را به شرح زیر ثبت نموده است :
        ///شماره سفارش : {1}
        ///درگاه بانکی : {2}
        ///مبلغ پرداختی : {3}
        ///کد رهگیری : {4}
        ///زمان تراکنش : {5}
        ///#پرداخت_در_محل.
        /// </summary>
        public static string Transaction_Add_Bot {
            get {
                return ResourceManager.GetString("Transaction_Add_Bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یکی از کاربران با نام {0} در ساعت {1} در رسمی آنلاین ثبت نام کرده است. 
        ///#ثبت_نام.
        /// </summary>
        public static string User_Register {
            get {
                return ResourceManager.GetString("User_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اکانت شما موقتا غیر فعال شده است ، برای اطلاعات بیشتر با مدیر سایت ارتباط برقرار نمایید.
        /// </summary>
        public static string UserBlock {
            get {
                return ResourceManager.GetString("UserBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این نام کاربری استفاده شده است.
        /// </summary>
        public static string UsernameExist {
            get {
                return ResourceManager.GetString("UsernameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر مورد نظر یافت نشد.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAME عزیز، سفارش شماره {0} قیمت گذاری گردید. لطفا برای مشاهده فاکتور بر روی لینک زیر کلیک کنید:
        ///http://panel.rasmiOnline.com.
        /// </summary>
        public static string Waiting_For_Payment {
            get {
                return ResourceManager.GetString("Waiting_For_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور اشتباه است.
        /// </summary>
        public static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری با رمز عبور اشتباه می باشد.
        /// </summary>
        public static string WrongUsernameOrPassword {
            get {
                return ResourceManager.GetString("WrongUsernameOrPassword", resourceCulture);
            }
        }
    }
}
