//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RasmiOnline.Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DisplayName {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayName() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RasmiOnline.Domain.Properties.DisplayName", typeof(DisplayName).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرجع تایید کننده.
        /// </summary>
        public static string AboveReference {
            get {
                return ResourceManager.GetString("AboveReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موفق.
        /// </summary>
        public static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره حساب.
        /// </summary>
        public static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام لاتین اکشن.
        /// </summary>
        public static string ActionName {
            get {
                return ResourceManager.GetString("ActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام فارسی اکشن.
        /// </summary>
        public static string ActionNameFa {
            get {
                return ResourceManager.GetString("ActionNameFa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسکن پاسپورت.
        /// </summary>
        public static string AttachmentIdentity {
            get {
                return ResourceManager.GetString("AttachmentIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسکن مدارک .
        /// </summary>
        public static string AttachmentOrderFiles {
            get {
                return ResourceManager.GetString("AttachmentOrderFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسکن فایل های ترجمه.
        /// </summary>
        public static string AttachmentTranslation {
            get {
                return ResourceManager.GetString("AttachmentTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AttachmentType.
        /// </summary>
        public static string AttachmentType {
            get {
                return ResourceManager.GetString("AttachmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authority.
        /// </summary>
        public static string Authority {
            get {
                return ResourceManager.GetString("Authority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارت های بانکی.
        /// </summary>
        public static string BankCard {
            get {
                return ResourceManager.GetString("BankCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام بانک.
        /// </summary>
        public static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروع.
        /// </summary>
        public static string Begin {
            get {
                return ResourceManager.GetString("Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تولد میلادی.
        /// </summary>
        public static string BirthDateMi {
            get {
                return ResourceManager.GetString("BirthDateMi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به نماینده رسمی آنلاین تحویل میدهم.
        /// </summary>
        public static string ByDeliveryMan {
            get {
                return ResourceManager.GetString("ByDeliveryMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آنلاین(درگاه بانکی).
        /// </summary>
        public static string ByGateway {
            get {
                return ResourceManager.GetString("ByGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال پستی(ویژه شهرستان).
        /// </summary>
        public static string ByPost {
            get {
                return ResourceManager.GetString("ByPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغو سفارش.
        /// </summary>
        public static string CancledOrder {
            get {
                return ResourceManager.GetString("CancledOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه لغو سفارش.
        /// </summary>
        public static string CancledOrderFee {
            get {
                return ResourceManager.GetString("CancledOrderFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره کارت بانکی.
        /// </summary>
        public static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان گروه بندی.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سقف.
        /// </summary>
        public static string Ceiling {
            get {
                return ResourceManager.GetString("Ceiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعدادکاراکتر کد.
        /// </summary>
        public static string CodeLength {
            get {
                return ResourceManager.GetString("CodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع کد.
        /// </summary>
        public static string CodeType {
            get {
                return ResourceManager.GetString("CodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات خود را اینجا بنویسید.
        /// </summary>
        public static string ConfirmComment {
            get {
                return ResourceManager.GetString("ConfirmComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید گذرواژه.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کنترلر.
        /// </summary>
        public static string Controller {
            get {
                return ResourceManager.GetString("Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسخه اضافی.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه هر نسخه اضافی.
        /// </summary>
        public static string CopyPrice {
            get {
                return ResourceManager.GetString("CopyPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه نسخه اضافی(غیر انگلیسی).
        /// </summary>
        public static string CopyPrice_OthersLang {
            get {
                return ResourceManager.GetString("CopyPrice_OthersLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گذرواژه جاری.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روز کاری تحویل مدارک.
        /// </summary>
        public static string DayToDelivery {
            get {
                return ResourceManager.GetString("DayToDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تحویل ترجمه.
        /// </summary>
        public static string DeliverFiles_DateSh {
            get {
                return ResourceManager.GetString("DeliverFiles_DateSh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خودم تحویل میدهم.
        /// </summary>
        public static string DeliverNyMySelf {
            get {
                return ResourceManager.GetString("DeliverNyMySelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحویل ترجمه.
        /// </summary>
        public static string DeliveryFiles {
            get {
                return ResourceManager.GetString("DeliveryFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استعلام نرخ و ثبت سفارش.
        /// </summary>
        public static string Detailed {
            get {
                return ResourceManager.GetString("Detailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع تخفیف.
        /// </summary>
        public static string DiscountType {
            get {
                return ResourceManager.GetString("DiscountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدارک تحویل گرفته شده اند.
        /// </summary>
        public static string DocsBeenRecieved {
            get {
                return ResourceManager.GetString("DocsBeenRecieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع مدرک.
        /// </summary>
        public static string DocumentType {
            get {
                return ResourceManager.GetString("DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتمام.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ انفضا.
        /// </summary>
        public static string ExpireDate {
            get {
                return ResourceManager.GetString("ExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفارش آسان.
        /// </summary>
        public static string Express {
            get {
                return ResourceManager.GetString("Express", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عربی.
        /// </summary>
        public static string Fa_Ar {
            get {
                return ResourceManager.GetString("Fa_Ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انگلیسی.
        /// </summary>
        public static string Fa_En {
            get {
                return ResourceManager.GetString("Fa_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرانسه.
        /// </summary>
        public static string Fa_Fr {
            get {
                return ResourceManager.GetString("Fa_Fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آلمانی.
        /// </summary>
        public static string Fa_Gr {
            get {
                return ResourceManager.GetString("Fa_Gr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایتالیایی.
        /// </summary>
        public static string Fa_It {
            get {
                return ResourceManager.GetString("Fa_It", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اردو.
        /// </summary>
        public static string Fa_Or {
            get {
                return ResourceManager.GetString("Fa_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روسی.
        /// </summary>
        public static string Fa_Ru {
            get {
                return ResourceManager.GetString("Fa_Ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استانبولی.
        /// </summary>
        public static string Fa_Tr {
            get {
                return ResourceManager.GetString("Fa_Tr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیتم فاکتور.
        /// </summary>
        public static string FactorItem {
            get {
                return ResourceManager.GetString("FactorItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ناموفق.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام پدر.
        /// </summary>
        public static string FatherName {
            get {
                return ResourceManager.GetString("FatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام پدر( انگلیسی ).
        /// </summary>
        public static string FatherNameEn {
            get {
                return ResourceManager.GetString("FatherNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileExtention.
        /// </summary>
        public static string FileExtention {
            get {
                return ResourceManager.GetString("FileExtention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام فایل.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileSize.
        /// </summary>
        public static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل سفارش برای ارسال رایگان.
        /// </summary>
        public static string FreeDeliveryMinOrderPrice {
            get {
                return ResourceManager.GetString("FreeDeliveryMinOrderPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس کامل.
        /// </summary>
        public static string FullAddress {
            get {
                return ResourceManager.GetString("FullAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام  کامل.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کامل (انگلیسی).
        /// </summary>
        public static string FullNameEN {
            get {
                return ResourceManager.GetString("FullNameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت فایل.
        /// </summary>
        public static string GetFiles {
            get {
                return ResourceManager.GetString("GetFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایه (آیکن).
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فوری.
        /// </summary>
        public static string Immediate {
            get {
                return ResourceManager.GetString("Immediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت در محل(کارتخوان).
        /// </summary>
        public static string InPerson {
            get {
                return ResourceManager.GetString("InPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال پردازش.
        /// </summary>
        public static string InProcessing {
            get {
                return ResourceManager.GetString("InProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ثبت.
        /// </summary>
        public static string InsertDateMi {
            get {
                return ResourceManager.GetString("InsertDateMi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ثبت.
        /// </summary>
        public static string InsertDateSh {
            get {
                return ResourceManager.GetString("InsertDateSh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ip.
        /// </summary>
        public static string Ip {
            get {
                return ResourceManager.GetString("Ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال/غیرفعال.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسدود شده.
        /// </summary>
        public static string IsBlock {
            get {
                return ResourceManager.GetString("IsBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید توسط مشتری.
        /// </summary>
        public static string IsConfirmedByClient {
            get {
                return ResourceManager.GetString("IsConfirmedByClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه دفتری.
        /// </summary>
        public static string IsConst {
            get {
                return ResourceManager.GetString("IsConst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیشفرض.
        /// </summary>
        public static string IsDefault {
            get {
                return ResourceManager.GetString("IsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف شده.
        /// </summary>
        public static string IsDeleted {
            get {
                return ResourceManager.GetString("IsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قابلیت اعمال تخفیف.
        /// </summary>
        public static string IsDiscountable {
            get {
                return ResourceManager.GetString("IsDiscountable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد کاربر.
        /// </summary>
        public static string IsFirstTime {
            get {
                return ResourceManager.GetString("IsFirstTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرکاربرد.
        /// </summary>
        public static string IsMustlyUse {
            get {
                return ResourceManager.GetString("IsMustlyUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع استفاده.
        /// </summary>
        public static string IsOneTime {
            get {
                return ResourceManager.GetString("IsOneTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیتم قیمت گذاری.
        /// </summary>
        public static string IsPricingItem {
            get {
                return ResourceManager.GetString("IsPricingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت.
        /// </summary>
        public static string IsSuccess {
            get {
                return ResourceManager.GetString("IsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استفاده شده.
        /// </summary>
        public static string IsUsed {
            get {
                return ResourceManager.GetString("IsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قابل نمایش.
        /// </summary>
        public static string IsVisible {
            get {
                return ResourceManager.GetString("IsVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemDescription.
        /// </summary>
        public static string ItemDescription {
            get {
                return ResourceManager.GetString("ItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برچسب.
        /// </summary>
        public static string Lable {
            get {
                return ResourceManager.GetString("Lable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زبان ترجمه.
        /// </summary>
        public static string LangType {
            get {
                return ResourceManager.GetString("LangType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخرین ورود.
        /// </summary>
        public static string LastLoginDate {
            get {
                return ResourceManager.GetString("LastLoginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محدودیت باز بودن سفارش در روز.
        /// </summary>
        public static string LimitOrderOpenDay {
            get {
                return ResourceManager.GetString("LimitOrderOpenDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مختصات جغرافیایی.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogData.
        /// </summary>
        public static string LogData {
            get {
                return ResourceManager.GetString("LogData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه تجاری.
        /// </summary>
        public static string MerchantId {
            get {
                return ResourceManager.GetString("MerchantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیام.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع پیام.
        /// </summary>
        public static string MessageType {
            get {
                return ResourceManager.GetString("MessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل.
        /// </summary>
        public static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام درگاه.
        /// </summary>
        public static string NameOfGateway {
            get {
                return ResourceManager.GetString("NameOfGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی.
        /// </summary>
        public static string NationalCode {
            get {
                return ResourceManager.GetString("NationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گذرواژه جدید.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام دفتر ترجمه.
        /// </summary>
        public static string OfficeName {
            get {
                return ResourceManager.GetString("OfficeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتقال به دفتر ترجمه.
        /// </summary>
        public static string OfficeUserId {
            get {
                return ResourceManager.GetString("OfficeUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروع ثبت سفارش.
        /// </summary>
        public static string OrderBegin {
            get {
                return ResourceManager.GetString("OrderBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزییات سفارش.
        /// </summary>
        public static string OrderDetail {
            get {
                return ResourceManager.GetString("OrderDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع مدرک.
        /// </summary>
        public static string OrderItemType {
            get {
                return ResourceManager.GetString("OrderItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره سفارش.
        /// </summary>
        public static string OrderNumber {
            get {
                return ResourceManager.GetString("OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اولویت نمایش.
        /// </summary>
        public static string OrderPriority {
            get {
                return ResourceManager.GetString("OrderPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفارشات.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت سفارش.
        /// </summary>
        public static string OrderStatus {
            get {
                return ResourceManager.GetString("OrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان سفارش.
        /// </summary>
        public static string OrderTitle {
            get {
                return ResourceManager.GetString("OrderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شاخه والد.
        /// </summary>
        public static string ParentId {
            get {
                return ResourceManager.GetString("ParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گذرواژه.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسویه نهایی.
        /// </summary>
        public static string PayAllFactor {
            get {
                return ResourceManager.GetString("PayAllFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روش تحویل مدارک.
        /// </summary>
        public static string PaymentDeliveryType {
            get {
                return ResourceManager.GetString("PaymentDeliveryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درگاه پرداخت.
        /// </summary>
        public static string PaymentGatewayId {
            get {
                return ResourceManager.GetString("PaymentGatewayId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع پرداخت.
        /// </summary>
        public static string PaymentType {
            get {
                return ResourceManager.GetString("PaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیش فاکتور.
        /// </summary>
        public static string PreFactor {
            get {
                return ResourceManager.GetString("PreFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت واحد.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت(غیر انگلیسی).
        /// </summary>
        public static string Price_OthersLang {
            get {
                return ResourceManager.GetString("Price_OthersLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه بندی.
        /// </summary>
        public static string PricingItemCategoryId {
            get {
                return ResourceManager.GetString("PricingItemCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قالب بندی.
        /// </summary>
        public static string PricingItemTemplate {
            get {
                return ResourceManager.GetString("PricingItemTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گیرنده.
        /// </summary>
        public static string Receiver {
            get {
                return ResourceManager.GetString("Receiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازیابی کلمه عبور.
        /// </summary>
        public static string RecoverPassword {
            get {
                return ResourceManager.GetString("RecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد دعوت.
        /// </summary>
        public static string ReferralCode {
            get {
                return ResourceManager.GetString("ReferralCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سهم معرف ( درصد ).
        /// </summary>
        public static string ReferralPercent {
            get {
                return ResourceManager.GetString("ReferralPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ثبت نام میلادی.
        /// </summary>
        public static string RegisterDateMi {
            get {
                return ResourceManager.GetString("RegisterDateMi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ثبت نام.
        /// </summary>
        public static string RegisterDateSh {
            get {
                return ResourceManager.GetString("RegisterDateSh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرا بخاطر بسپار.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار گذرواژه.
        /// </summary>
        public static string RepeatePassword {
            get {
                return ResourceManager.GetString("RepeatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ربات تلگرام.
        /// </summary>
        public static string RoboTele {
            get {
                return ResourceManager.GetString("RoboTele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان لاتین.
        /// </summary>
        public static string RoleNameEn {
            get {
                return ResourceManager.GetString("RoleNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان فارسی.
        /// </summary>
        public static string RoleNameFa {
            get {
                return ResourceManager.GetString("RoleNameFa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت سفارش.
        /// </summary>
        public static string SavedOrder {
            get {
                return ResourceManager.GetString("SavedOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام فرستنده.
        /// </summary>
        public static string Sender {
            get {
                return ResourceManager.GetString("Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیامک.
        /// </summary>
        public static string Sms {
            get {
                return ResourceManager.GetString("Sms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ شروع.
        /// </summary>
        public static string StartDateSh {
            get {
                return ResourceManager.GetString("StartDateSh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروع فرایند ترجمه.
        /// </summary>
        public static string StartTranslation {
            get {
                return ResourceManager.GetString("StartTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید مرجع بالا.
        /// </summary>
        public static string SubmitDescription {
            get {
                return ResourceManager.GetString("SubmitDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارایه پیش نویس.
        /// </summary>
        public static string SubmitDraft {
            get {
                return ResourceManager.GetString("SubmitDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن.
        /// </summary>
        public static string Tel {
            get {
                return ResourceManager.GetString("Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موضوع.
        /// </summary>
        public static string TitleComment {
            get {
                return ResourceManager.GetString("TitleComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت نهایی.
        /// </summary>
        public static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد رهگیری.
        /// </summary>
        public static string TrackingId {
            get {
                return ResourceManager.GetString("TrackingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransactionStatus.
        /// </summary>
        public static string TransactionStatus {
            get {
                return ResourceManager.GetString("TransactionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترجمه.
        /// </summary>
        public static string Translation {
            get {
                return ResourceManager.GetString("Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ترجمه.
        /// </summary>
        public static string TranslationDate {
            get {
                return ResourceManager.GetString("TranslationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واحد.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بارگذاری مدارک.
        /// </summary>
        public static string UploadFiles {
            get {
                return ResourceManager.GetString("UploadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری(ایمیل).
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری(ایمیل).
        /// </summary>
        public static string UsernameOrPassword {
            get {
                return ResourceManager.GetString("UsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربران.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ اعتبار از.
        /// </summary>
        public static string ValidFromDateSh {
            get {
                return ResourceManager.GetString("ValidFromDateSh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ اعتبار تا.
        /// </summary>
        public static string ValidToDateSh {
            get {
                return ResourceManager.GetString("ValidToDateSh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسخه.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه (ویو).
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درانتظار دریافت مدارک توسط نماینده.
        /// </summary>
        public static string WaitForDeliverDocumentByPeyk {
            get {
                return ResourceManager.GetString("WaitForDeliverDocumentByPeyk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در انتظار ارسال مدارک از طریق پست.
        /// </summary>
        public static string WaitForDeliverDocumentByPost {
            get {
                return ResourceManager.GetString("WaitForDeliverDocumentByPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در انتظار تحویل مدارک توسط کاربر.
        /// </summary>
        public static string WaitForDeliverDocumentByUser {
            get {
                return ResourceManager.GetString("WaitForDeliverDocumentByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در انتظار پرداخت.
        /// </summary>
        public static string WaitForPayment {
            get {
                return ResourceManager.GetString("WaitForPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در انتظار تماس پشتیبان.
        /// </summary>
        public static string WaitForPricing {
            get {
                return ResourceManager.GetString("WaitForPricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تذکرات مهم.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعات مراجعه حضوری.
        /// </summary>
        public static string WorkHour {
            get {
                return ResourceManager.GetString("WorkHour", resourceCulture);
            }
        }
    }
}
