// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC
{
    public class OrderController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _Layout = "_Layout";
                public readonly string CompleteOrder = "CompleteOrder";
                public readonly string ConfirmDraft = "ConfirmDraft";
                public readonly string Detail = "Detail";
                public readonly string Detail_Mobile = "Detail.Mobile";
                public readonly string DetailedAdd = "DetailedAdd";
                public readonly string DetailedAdd_Mobile = "DetailedAdd.Mobile";
                public readonly string History = "History";
                public readonly string NotFound = "NotFound";
                public readonly string Pay = "Pay";
                public readonly string Pay_Mobile = "Pay.Mobile";
                public readonly string PayAllFactor = "PayAllFactor";
                public readonly string Search = "Search";
            }
            public readonly string _Layout = "~/Views/Order/_Layout.cshtml";
            public readonly string CompleteOrder = "~/Views/Order/CompleteOrder.cshtml";
            public readonly string ConfirmDraft = "~/Views/Order/ConfirmDraft.cshtml";
            public readonly string Detail = "~/Views/Order/Detail.cshtml";
            public readonly string Detail_Mobile = "~/Views/Order/Detail.Mobile.cshtml";
            public readonly string DetailedAdd = "~/Views/Order/DetailedAdd.cshtml";
            public readonly string DetailedAdd_Mobile = "~/Views/Order/DetailedAdd.Mobile.cshtml";
            public readonly string History = "~/Views/Order/History.cshtml";
            public readonly string NotFound = "~/Views/Order/NotFound.cshtml";
            public readonly string Pay = "~/Views/Order/Pay.cshtml";
            public readonly string Pay_Mobile = "~/Views/Order/Pay.Mobile.cshtml";
            public readonly string PayAllFactor = "~/Views/Order/PayAllFactor.cshtml";
            public readonly string Search = "~/Views/Order/Search.cshtml";
            static readonly _PartialsClass s_Partials = new _PartialsClass();
            public _PartialsClass Partials { get { return s_Partials; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _PartialsClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string _AddOrderItem = "_AddOrderItem";
                    public readonly string _AddOrderItem_Mobile = "_AddOrderItem.Mobile";
                    public readonly string _DetailedAddTimeLine = "_DetailedAddTimeLine";
                    public readonly string _DetailedSummary = "_DetailedSummary";
                    public readonly string _DetailedSummary_Mobile = "_DetailedSummary.Mobile";
                    public readonly string _GetOrderPaymentInfo = "_GetOrderPaymentInfo";
                    public readonly string _ListForMobile = "_ListForMobile";
                    public readonly string _OrderList = "_OrderList";
                    public readonly string _SearchList = "_SearchList";
                    public readonly string _SearchOrder = "_SearchOrder";
                    public readonly string _SelectDeliveryType = "_SelectDeliveryType";
                    public readonly string _SelectPaymentType = "_SelectPaymentType";
                    public readonly string _Show = "_Show";
                    public readonly string _Summary = "_Summary";
                    public readonly string _SummaryHeader = "_SummaryHeader";
                }
                public readonly string _AddOrderItem = "~/Views/Order/Partials/_AddOrderItem.cshtml";
                public readonly string _AddOrderItem_Mobile = "~/Views/Order/Partials/_AddOrderItem.Mobile.cshtml";
                public readonly string _DetailedAddTimeLine = "~/Views/Order/Partials/_DetailedAddTimeLine.cshtml";
                public readonly string _DetailedSummary = "~/Views/Order/Partials/_DetailedSummary.cshtml";
                public readonly string _DetailedSummary_Mobile = "~/Views/Order/Partials/_DetailedSummary.Mobile.cshtml";
                public readonly string _GetOrderPaymentInfo = "~/Views/Order/Partials/_GetOrderPaymentInfo.cshtml";
                public readonly string _ListForMobile = "~/Views/Order/Partials/_ListForMobile.cshtml";
                public readonly string _OrderList = "~/Views/Order/Partials/_OrderList.cshtml";
                public readonly string _SearchList = "~/Views/Order/Partials/_SearchList.cshtml";
                public readonly string _SearchOrder = "~/Views/Order/Partials/_SearchOrder.cshtml";
                public readonly string _SelectDeliveryType = "~/Views/Order/Partials/_SelectDeliveryType.cshtml";
                public readonly string _SelectPaymentType = "~/Views/Order/Partials/_SelectPaymentType.cshtml";
                public readonly string _Show = "~/Views/Order/Partials/_Show.cshtml";
                public readonly string _Summary = "~/Views/Order/Partials/_Summary.cshtml";
                public readonly string _SummaryHeader = "~/Views/Order/Partials/_SummaryHeader.cshtml";
            }
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
