// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace RasmiOnline.Console.Controllers
{
    public partial class TransactionController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected TransactionController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult PayVerify()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.PayVerify);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult SadadVerify()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.SadadVerify);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ViewResult ZarinPalVerify()
        {
            return new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.ZarinPalVerify);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.PartialViewResult List()
        {
            return new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.List);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.PartialViewResult AddableList()
        {
            return new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.AddableList);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult AddTransaction()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.AddTransaction);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult RemoveTransaction()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.RemoveTransaction);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.PartialViewResult EcommerceScript()
        {
            return new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.EcommerceScript);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult Read()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Read);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public TransactionController Actions { get { return MVC.Transaction; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Transaction";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Transaction";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string PayVerify = "PayVerify";
            public readonly string SadadVerify = "SadadVerify";
            public readonly string ZarinPalVerify = "ZarinPalVerify";
            public readonly string List = "List";
            public readonly string AddableList = "AddableList";
            public readonly string AddTransaction = "AddTransaction";
            public readonly string RemoveTransaction = "RemoveTransaction";
            public readonly string EcommerceScript = "EcommerceScript";
            public readonly string GetAllUnReadPayment = "GetAllUnReadPayment";
            public readonly string GetAllUnReadOfficePayment = "GetAllUnReadOfficePayment";
            public readonly string Read = "Read";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string PayVerify = "PayVerify";
            public const string SadadVerify = "SadadVerify";
            public const string ZarinPalVerify = "ZarinPalVerify";
            public const string List = "List";
            public const string AddableList = "AddableList";
            public const string AddTransaction = "AddTransaction";
            public const string RemoveTransaction = "RemoveTransaction";
            public const string EcommerceScript = "EcommerceScript";
            public const string GetAllUnReadPayment = "GetAllUnReadPayment";
            public const string GetAllUnReadOfficePayment = "GetAllUnReadOfficePayment";
            public const string Read = "Read";
        }


        static readonly ActionParamsClass_PayVerify s_params_PayVerify = new ActionParamsClass_PayVerify();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PayVerify PayVerifyParams { get { return s_params_PayVerify; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PayVerify
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_SadadVerify s_params_SadadVerify = new ActionParamsClass_SadadVerify();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SadadVerify SadadVerifyParams { get { return s_params_SadadVerify; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SadadVerify
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_ZarinPalVerify s_params_ZarinPalVerify = new ActionParamsClass_ZarinPalVerify();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ZarinPalVerify ZarinPalVerifyParams { get { return s_params_ZarinPalVerify; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ZarinPalVerify
        {
            public readonly string Status = "Status";
            public readonly string Authority = "Authority";
        }
        static readonly ActionParamsClass_List s_params_List = new ActionParamsClass_List();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_List ListParams { get { return s_params_List; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_List
        {
            public readonly string orderId = "orderId";
        }
        static readonly ActionParamsClass_AddableList s_params_AddableList = new ActionParamsClass_AddableList();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddableList AddableListParams { get { return s_params_AddableList; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddableList
        {
            public readonly string orderId = "orderId";
            public readonly string removeable = "removeable";
        }
        static readonly ActionParamsClass_AddTransaction s_params_AddTransaction = new ActionParamsClass_AddTransaction();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddTransaction AddTransactionParams { get { return s_params_AddTransaction; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddTransaction
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_RemoveTransaction s_params_RemoveTransaction = new ActionParamsClass_RemoveTransaction();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RemoveTransaction RemoveTransactionParams { get { return s_params_RemoveTransaction; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RemoveTransaction
        {
            public readonly string orderId = "orderId";
            public readonly string transactionId = "transactionId";
        }
        static readonly ActionParamsClass_EcommerceScript s_params_EcommerceScript = new ActionParamsClass_EcommerceScript();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EcommerceScript EcommerceScriptParams { get { return s_params_EcommerceScript; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EcommerceScript
        {
            public readonly string orderId = "orderId";
            public readonly string price = "price";
        }
        static readonly ActionParamsClass_Read s_params_Read = new ActionParamsClass_Read();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Read ReadParams { get { return s_params_Read; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Read
        {
            public readonly string transactionId = "transactionId";
            public readonly string isOffice = "isOffice";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Failed = "Failed";
                public readonly string Success = "Success";
            }
            public readonly string Failed = "~/Views/Transaction/Failed.cshtml";
            public readonly string Success = "~/Views/Transaction/Success.cshtml";
            static readonly _PartialsClass s_Partials = new _PartialsClass();
            public _PartialsClass Partials { get { return s_Partials; } }
            [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
            public partial class _PartialsClass
            {
                static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
                public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
                public class _ViewNamesClass
                {
                    public readonly string _AddableList = "_AddableList";
                    public readonly string _AllUnReadPayment = "_AllUnReadPayment";
                    public readonly string _EcommerceScript = "_EcommerceScript";
                    public readonly string _List = "_List";
                }
                public readonly string _AddableList = "~/Views/Transaction/Partials/_AddableList.cshtml";
                public readonly string _AllUnReadPayment = "~/Views/Transaction/Partials/_AllUnReadPayment.cshtml";
                public readonly string _EcommerceScript = "~/Views/Transaction/Partials/_EcommerceScript.cshtml";
                public readonly string _List = "~/Views/Transaction/Partials/_List.cshtml";
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_TransactionController : RasmiOnline.Console.Controllers.TransactionController
    {
        public T4MVC_TransactionController() : base(Dummy.Instance) { }

        [NonAction]
        partial void PayVerifyOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, RasmiOnline.Domain.Dto.PayRedirectModel model);

        [NonAction]
        public override System.Web.Mvc.ViewResult PayVerify(RasmiOnline.Domain.Dto.PayRedirectModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.PayVerify);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            PayVerifyOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void SadadVerifyOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, RasmiOnline.Console.PaymentStrategy.SadadPurchaseResult model);

        [NonAction]
        public override System.Web.Mvc.ViewResult SadadVerify(RasmiOnline.Console.PaymentStrategy.SadadPurchaseResult model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.SadadVerify);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            SadadVerifyOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void ZarinPalVerifyOverride(T4MVC_System_Web_Mvc_ViewResult callInfo, string Status, string Authority);

        [NonAction]
        public override System.Web.Mvc.ViewResult ZarinPalVerify(string Status, string Authority)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ViewResult(Area, Name, ActionNames.ZarinPalVerify);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Status", Status);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "Authority", Authority);
            ZarinPalVerifyOverride(callInfo, Status, Authority);
            return callInfo;
        }

        [NonAction]
        partial void ListOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, int orderId);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult List(int orderId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.List);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "orderId", orderId);
            ListOverride(callInfo, orderId);
            return callInfo;
        }

        [NonAction]
        partial void AddableListOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, int orderId, bool removeable);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult AddableList(int orderId, bool removeable)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.AddableList);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "orderId", orderId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "removeable", removeable);
            AddableListOverride(callInfo, orderId, removeable);
            return callInfo;
        }

        [NonAction]
        partial void AddTransactionOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, RasmiOnline.Domain.Entity.Transaction model);

        [NonAction]
        public override System.Web.Mvc.JsonResult AddTransaction(RasmiOnline.Domain.Entity.Transaction model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.AddTransaction);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            AddTransactionOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void RemoveTransactionOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int orderId, int transactionId);

        [NonAction]
        public override System.Web.Mvc.JsonResult RemoveTransaction(int orderId, int transactionId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.RemoveTransaction);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "orderId", orderId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "transactionId", transactionId);
            RemoveTransactionOverride(callInfo, orderId, transactionId);
            return callInfo;
        }

        [NonAction]
        partial void EcommerceScriptOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo, int orderId, int price);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult EcommerceScript(int orderId, int price)
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.EcommerceScript);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "orderId", orderId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "price", price);
            EcommerceScriptOverride(callInfo, orderId, price);
            return callInfo;
        }

        [NonAction]
        partial void GetAllUnReadPaymentOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult GetAllUnReadPayment()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.GetAllUnReadPayment);
            GetAllUnReadPaymentOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetAllUnReadOfficePaymentOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult GetAllUnReadOfficePayment()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.GetAllUnReadOfficePayment);
            GetAllUnReadOfficePaymentOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ReadOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, int transactionId, bool isOffice);

        [NonAction]
        public override System.Web.Mvc.JsonResult Read(int transactionId, bool isOffice)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Read);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "transactionId", transactionId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "isOffice", isOffice);
            ReadOverride(callInfo, transactionId, isOffice);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
