//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RasmiOnline.Console.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RasmiOnline.Console.Properties.LocalMessage", typeof(LocalMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد تخفیف جدید.
        /// </summary>
        public static string AddDiscount {
            get {
                return ResourceManager.GetString("AddDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما در اینجا قادر خواهید بود تخفیفات مورد نظر را با توجه به نیاز خود ایجاد نمائید.
        /// </summary>
        public static string AddDiscountDescription {
            get {
                return ResourceManager.GetString("AddDiscountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + افزودن آدرس جدید.
        /// </summary>
        public static string AddNewAddress {
            get {
                return ResourceManager.GetString("AddNewAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت کارت بانکی جدید.
        /// </summary>
        public static string AddNewBankCard {
            get {
                return ResourceManager.GetString("AddNewBankCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت کانال جدید.
        /// </summary>
        public static string AddNewChannel {
            get {
                return ResourceManager.GetString("AddNewChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن آدرس دفتر ترجمه.
        /// </summary>
        public static string AddNewOfficeAddress {
            get {
                return ResourceManager.GetString("AddNewOfficeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهت افزودن مدرک جدید، نوع آن را تایپ نمایید.
        /// </summary>
        public static string AddNewPricingItem {
            get {
                return ResourceManager.GetString("AddNewPricingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت سفارش.
        /// </summary>
        public static string AddOrder {
            get {
                return ResourceManager.GetString("AddOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن درگاه جدید.
        /// </summary>
        public static string AddPaymentGateway {
            get {
                return ResourceManager.GetString("AddPaymentGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن آیتم سفارش.
        /// </summary>
        public static string AddPricingItem {
            get {
                return ResourceManager.GetString("AddPricingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس های ثبت شده.
        /// </summary>
        public static string Addresses {
            get {
                return ResourceManager.GetString("Addresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن نقش.
        /// </summary>
        public static string AddRole {
            get {
                return ResourceManager.GetString("AddRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفارش شما با کد &lt;span class=&apos;order-number&apos;&gt;{0}&lt;/span&gt; با موفقیت ثبت شد&lt;br /&gt; کارشناسان مجموعه رسمی آنلاین به زودی برای هماهنگی های لازم با شما تماس می گیرند.
        /// </summary>
        public static string AddSummaryHeaderText {
            get {
                return ResourceManager.GetString("AddSummaryHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفارش شما با کد &lt;span class=&apos;order-number&apos;&gt;{0}&lt;/span&gt; با موفقیت ثبت شد. کارشناسان مجموعه رسمی آنلاین به زودی برای هماهنگی های لازم با شما تماس می گیرند.
        /// </summary>
        public static string AddSummaryHeaderTextForMobile {
            get {
                return ResourceManager.GetString("AddSummaryHeaderTextForMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن کاربر جدید.
        /// </summary>
        public static string AddUser {
            get {
                return ResourceManager.GetString("AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در این صفحه امکان ثبت نام کاربر جدید وجود دارد.
        /// </summary>
        public static string AddUserDescription {
            get {
                return ResourceManager.GetString("AddUserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن صفحه (ویو).
        /// </summary>
        public static string AddView {
            get {
                return ResourceManager.GetString("AddView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قوانین را مطالعه و پذیرفتم..
        /// </summary>
        public static string AgreeWithRules {
            get {
                return ResourceManager.GetString("AgreeWithRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همه موارد.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازگشت.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست داده شده معتبر نمی باشد.
        /// </summary>
        public static string BadRequest {
            get {
                return ResourceManager.GetString("BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت کارت های بانکی.
        /// </summary>
        public static string BankCardManagment {
            get {
                return ResourceManager.GetString("BankCardManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توسط کاربر.
        /// </summary>
        public static string ByMyself {
            get {
                return ResourceManager.GetString("ByMyself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغو.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه بندی.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر رمز عبور.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر وضعیت.
        /// </summary>
        public static string ChangeStatus {
            get {
                return ResourceManager.GetString("ChangeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت کانال های تبلیغاتی.
        /// </summary>
        public static string ChannelManagement {
            get {
                return ResourceManager.GetString("ChannelManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکمیل سفارش.
        /// </summary>
        public static string CompleteOrder {
            get {
                return ResourceManager.GetString("CompleteOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای تکمیل سفارش شما بایستی مبلغ {0} تومان پرداخت نمایید..
        /// </summary>
        public static string CompleteOrderPaymentGatewaysTitle {
            get {
                return ResourceManager.GetString("CompleteOrderPaymentGatewaysTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید پیش نویس.
        /// </summary>
        public static string ConfirmDraft {
            get {
                return ResourceManager.GetString("ConfirmDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی لطفا پس از ملاحظه فایلهای مورد نظر اقدام به تایید نمایید.
        /// </summary>
        public static string ConfirmDraftText {
            get {
                return ResourceManager.GetString("ConfirmDraftText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید فاکتور.
        /// </summary>
        public static string ConfirmFactor {
            get {
                return ResourceManager.GetString("ConfirmFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.rasmionline.com.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه ها.
        /// </summary>
        public static string Costs {
            get {
                return ResourceManager.GetString("Costs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از تاریخ.
        /// </summary>
        public static string DateFrom {
            get {
                return ResourceManager.GetString("DateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا تاریخ.
        /// </summary>
        public static string DateTo {
            get {
                return ResourceManager.GetString("DateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} روز کاری پس از پرداخت هزینه سفارش.
        /// </summary>
        public static string DayToDeliveryFormat {
            get {
                return ResourceManager.GetString("DayToDeliveryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف مدرک.
        /// </summary>
        public static string DeletePricingItem {
            get {
                return ResourceManager.GetString("DeletePricingItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف نقش.
        /// </summary>
        public static string DeleteRole {
            get {
                return ResourceManager.GetString("DeleteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف صفحه.
        /// </summary>
        public static string DeleteView {
            get {
                return ResourceManager.GetString("DeleteView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خودم تحویل میدهم.
        /// </summary>
        public static string DeliverByMyself {
            get {
                return ResourceManager.GetString("DeliverByMyself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به نماینده رسمی آنلاین تحویل میدهم.
        /// </summary>
        public static string DeliverByPost {
            get {
                return ResourceManager.GetString("DeliverByPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تخفیف.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد تخفیف.
        /// </summary>
        public static string DiscountCode {
            get {
                return ResourceManager.GetString("DiscountCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتمام ثبت سفارش.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ندارد.
        /// </summary>
        public static string DoseNotHave {
            get {
                return ResourceManager.GetString("DoseNotHave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دانلود.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد {0} رکورد با موفقیت در پاسخ به درخواست شما پیدا و فایل اکسل آن ایجاد شد.
        /// </summary>
        public static string DownloadFileIsSuccessful {
            get {
                return ResourceManager.GetString("DownloadFileIsSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش درگاه بانکی.
        /// </summary>
        public static string EditPaymentGateway {
            get {
                return ResourceManager.GetString("EditPaymentGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش نقش.
        /// </summary>
        public static string EditRole {
            get {
                return ResourceManager.GetString("EditRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش صفحه.
        /// </summary>
        public static string EditView {
            get {
                return ResourceManager.GetString("EditView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل وارد نشده است.
        /// </summary>
        public static string EmailNotEntered {
            get {
                return ResourceManager.GetString("EmailNotEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری را وارد نمایید.
        /// </summary>
        public static string EnteredEmail {
            get {
                return ResourceManager.GetString("EnteredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل را وارد نمائید.
        /// </summary>
        public static string EnteredMobileNumber {
            get {
                return ResourceManager.GetString("EnteredMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متاسفانه در اجرای درخواست دانلود فایل شما خطایی رخ داده است. لطفا مجددا سعی نمائید.
        /// </summary>
        public static string ErroInDownloadFile {
            get {
                return ResourceManager.GetString("ErroInDownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای سیستمی.
        /// </summary>
        public static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صدور و دریافت فایل اکسل از لیست.
        /// </summary>
        public static string ExportAndDownloadExcelFile {
            get {
                return ResourceManager.GetString("ExportAndDownloadExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در زیر شما امکان درخواست و دریافت فایل اکسل از جدول مورد نظر را دارید.
        /// </summary>
        public static string ExportAndDownloadExcelFileDescription {
            get {
                return ResourceManager.GetString("ExportAndDownloadExcelFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تک کابره.
        /// </summary>
        public static string FirstTime {
            get {
                return ResourceManager.GetString("FirstTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبورم را فراموش کرده ام!.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چند کاربره.
        /// </summary>
        public static string FreeTime {
            get {
                return ResourceManager.GetString("FreeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام  و نام خانوادگی.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دارد.
        /// </summary>
        public static string HasIt {
            get {
                return ResourceManager.GetString("HasIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ثبت.
        /// </summary>
        public static string InsertDate {
            get {
                return ResourceManager.GetString("InsertDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام لاتین اکشن الزامی می باشد.
        /// </summary>
        public static string InvalidActionName {
            get {
                return ResourceManager.GetString("InvalidActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سقف وارد نشده است.
        /// </summary>
        public static string InvalidCelling {
            get {
                return ResourceManager.GetString("InvalidCelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع کد تخفیف انتخاب نشده است.
        /// </summary>
        public static string InvalidCodeType {
            get {
                return ResourceManager.GetString("InvalidCodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کنترلر الزامی می باشد.
        /// </summary>
        public static string InvalidControllerName {
            get {
                return ResourceManager.GetString("InvalidControllerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع تخفیف انتخاب نشده است.
        /// </summary>
        public static string InvalidDiscountType {
            get {
                return ResourceManager.GetString("InvalidDiscountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس ایمیل وارد شده معتبر نمی باشد.
        /// </summary>
        public static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات وارد شده صحیح نمی باشد.
        /// </summary>
        public static string InvalidFormData {
            get {
                return ResourceManager.GetString("InvalidFormData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایه (آیکن) برای سر گروه الزامی می باشد.
        /// </summary>
        public static string InvalidIcon {
            get {
                return ResourceManager.GetString("InvalidIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل وارد شده صحیح نمی باشد.
        /// </summary>
        public static string InvalidMobileNumber {
            get {
                return ResourceManager.GetString("InvalidMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش انتخاب شده معتبر نمی باشد.
        /// </summary>
        public static string InvalidSelectedRole {
            get {
                return ResourceManager.GetString("InvalidSelectedRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار وارد نشده است.
        /// </summary>
        public static string InvalidValue {
            get {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اقلام.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس برایم ایمیل شود.
        /// </summary>
        public static string IWantTheAddressToBeEmail {
            get {
                return ResourceManager.GetString("IWantTheAddressToBeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس برایم پیامک شود.
        /// </summary>
        public static string IWantTheAddressToBeSMS {
            get {
                return ResourceManager.GetString("IWantTheAddressToBeSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زبان ترجمه.
        /// </summary>
        public static string LangType {
            get {
                return ResourceManager.GetString("LangType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود به سیستم.
        /// </summary>
        public static string LoginToSystem {
            get {
                return ResourceManager.GetString("LoginToSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل.
        /// </summary>
        public static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره موبایل وارد نشده است.
        /// </summary>
        public static string MobileNumberNotEntered {
            get {
                return ResourceManager.GetString("MobileNumberNotEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تومان.
        /// </summary>
        public static string MoneyCurrency {
            get {
                return ResourceManager.GetString("MoneyCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چندبار مصرف.
        /// </summary>
        public static string MultipleTime {
            get {
                return ResourceManager.GetString("MultipleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی وارد نشده است.
        /// </summary>
        public static string NationalCodeNotEntered {
            get {
                return ResourceManager.GetString("NationalCodeNotEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرحله بعد.
        /// </summary>
        public static string NextStep {
            get {
                return ResourceManager.GetString("NextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خیر.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} انتخاب نشده است.
        /// </summary>
        public static string NotSelectedWithFormat {
            get {
                return ResourceManager.GetString("NotSelectedWithFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه خدمات دفتری.
        /// </summary>
        public static string OfficialCost {
            get {
                return ResourceManager.GetString("OfficialCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه دفتری.
        /// </summary>
        public static string OfficialPrice {
            get {
                return ResourceManager.GetString("OfficialPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باشه.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یکبار مصرف.
        /// </summary>
        public static string OneTime {
            get {
                return ResourceManager.GetString("OneTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات با خطا مواجه شد، لطفا دوباره سعی نمایید.
        /// </summary>
        public static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفارش.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروع فرایند سفارش.
        /// </summary>
        public static string OrderBegin {
            get {
                return ResourceManager.GetString("OrderBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جزئیات سفارش.
        /// </summary>
        public static string OrderDetail {
            get {
                return ResourceManager.GetString("OrderDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخچه سفارشات.
        /// </summary>
        public static string OrderHistory {
            get {
                return ResourceManager.GetString("OrderHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در زیر تاریخچه سفارشات شما لیست شده است.
        /// </summary>
        public static string OrderHistoryDescription {
            get {
                return ResourceManager.GetString("OrderHistoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفارش مورد نظر معتبر نمی باشد.
        /// </summary>
        public static string OrderIsNotValid {
            get {
                return ResourceManager.GetString("OrderIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در زیر 100 سفارش آخر بر اساس نوع وضعیت لیست شده است.
        /// </summary>
        public static string OrderItemsListWithStatus {
            get {
                return ResourceManager.GetString("OrderItemsListWithStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت سفارشات.
        /// </summary>
        public static string OrderManagment {
            get {
                return ResourceManager.GetString("OrderManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در زیر امکان مشاهده تعداد سفارشات بر اساس وضعیت آن ها وجود دارد. همچنین میتوانید با کلیک بر روی هر کدام لیست آنها را ببینید.
        /// </summary>
        public static string OrderManagmentDescription {
            get {
                return ResourceManager.GetString("OrderManagmentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدیهی است اشکال بوجود آمده از عدم تکمیل اطلاعات فوق به عهده شماست.
        /// </summary>
        public static string OrderNameWarning {
            get {
                return ResourceManager.GetString("OrderNameWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعیین اطلاعات سفارش و نحوه ارسال و دریافت مدارک.
        /// </summary>
        public static string OrderPurpose {
            get {
                return ResourceManager.GetString("OrderPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفارشات.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجوی سفارشات.
        /// </summary>
        public static string OrderSearch {
            get {
                return ResourceManager.GetString("OrderSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شاخه والد.
        /// </summary>
        public static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسیر.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسویه نهایی.
        /// </summary>
        public static string PaymentAllFactor {
            get {
                return ResourceManager.GetString("PaymentAllFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتصال به درگاه با خطا مواجه شد، لطفا مجددا تلاش نمایید.
        /// </summary>
        public static string PaymentConnectionFailed {
            get {
                return ResourceManager.GetString("PaymentConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت سفارش  {0}.
        /// </summary>
        public static string PaymentDescription {
            get {
                return ResourceManager.GetString("PaymentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات پرداخت کنسل شده ویا با خطا روبه رو شده است.
        /// </summary>
        public static string PaymentException {
            get {
                return ResourceManager.GetString("PaymentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درگاه پرداخت.
        /// </summary>
        public static string PaymentGateway {
            get {
                return ResourceManager.GetString("PaymentGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت درگاه های بانکی.
        /// </summary>
        public static string PaymentGatewayManagment {
            get {
                return ResourceManager.GetString("PaymentGatewayManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درگاه بانکی.
        /// </summary>
        public static string PaymentGateways {
            get {
                return ResourceManager.GetString("PaymentGateways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفارش شما با کد {0}، آماده پرداخت می باشد . برای شروع فرایند ترجمه، لطفا مبلغ فاکتور را پرداخت نمایید.
        /// </summary>
        public static string PayNotificationMessage {
            get {
                return ResourceManager.GetString("PayNotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا تاریخ را به صورت صحیح وارد کنید.
        /// </summary>
        public static string PleaseEnterACorrectDateTimeRange {
            get {
                return ResourceManager.GetString("PleaseEnterACorrectDateTimeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا انتخاب نمائید.
        /// </summary>
        public static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا نحوه ارسال مدارک را انتخاب نمایید.
        /// </summary>
        public static string PleaseSelectAddress {
            get {
                return ResourceManager.GetString("PleaseSelectAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توسط نماینده رسمی آنلاین.
        /// </summary>
        public static string PostIt {
            get {
                return ResourceManager.GetString("PostIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیش پرداخت.
        /// </summary>
        public static string PrePayment {
            get {
                return ResourceManager.GetString("PrePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرحله قبل.
        /// </summary>
        public static string PrevStep {
            get {
                return ResourceManager.GetString("PrevStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ سفارش.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تماس پشتیبان.
        /// </summary>
        public static string Pricing {
            get {
                return ResourceManager.GetString("Pricing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش مدرک.
        /// </summary>
        public static string PricingItemChannel {
            get {
                return ResourceManager.GetString("PricingItemChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجوی آیتم های قیمت گذاری.
        /// </summary>
        public static string PricingItemSearch {
            get {
                return ResourceManager.GetString("PricingItemSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پروفایل.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات شخصی.
        /// </summary>
        public static string Props {
            get {
                return ResourceManager.GetString("Props", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت سفارش سریع.
        /// </summary>
        public static string QuickAddOrder {
            get {
                return ResourceManager.GetString("QuickAddOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای ثبت سفارش شما بایستی حداقل مبلغ {0} تومان به عنوان پیش پرداخت واریز نمایید..
        /// </summary>
        public static string QuickAddOrderPaymentGatewaysTitle {
            get {
                return ResourceManager.GetString("QuickAddOrderPaymentGatewaysTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رکورد مورد نظر یافت نشد.
        /// </summary>
        public static string RecordsNotFound {
            get {
                return ResourceManager.GetString("RecordsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازیابی.
        /// </summary>
        public static string Recover {
            get {
                return ResourceManager.GetString("Recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازیابی رمز عبور.
        /// </summary>
        public static string RecoverPassword {
            get {
                return ResourceManager.GetString("RecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما اقدام به بازیابی رمز عبور در سایت {0} نموده اید، رمز عبور جدید شما عبارتست از: {1}.
        /// </summary>
        public static string RecoverPasswordSms {
            get {
                return ResourceManager.GetString("RecoverPasswordSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لینک تغییر رمز عبور به ایمیل شما ارسال گردید.
        /// </summary>
        public static string RecoverPasswordSuccesssMsg {
            get {
                return ResourceManager.GetString("RecoverPasswordSuccesssMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهت بازیابی رمز عبور، ایمیل خود را وارد نمایید.
        /// </summary>
        public static string RecoverPasswordText {
            get {
                return ResourceManager.GetString("RecoverPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کابری(ایمیل) جهت بازیابی.
        /// </summary>
        public static string RecoverUsername {
            get {
                return ResourceManager.GetString("RecoverUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در بازگشت از درگاه به سایت اصلی.
        /// </summary>
        public static string RedirectException {
            get {
                return ResourceManager.GetString("RedirectException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ثبت نام.
        /// </summary>
        public static string RegisterationDate {
            get {
                return ResourceManager.GetString("RegisterationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازنشانی.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر رمز انجام شد، بزودی به صفحه ورود منتقل میشوید.
        /// </summary>
        public static string ResetPasswordSuccesssMsg {
            get {
                return ResourceManager.GetString("ResetPasswordSuccesssMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازگشت.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجوی نقش ها.
        /// </summary>
        public static string RoleSearch {
            get {
                return ResourceManager.GetString("RoleSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ نقشی یافت نشد.
        /// </summary>
        public static string RolesNotFound {
            get {
                return ResourceManager.GetString("RolesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ردیف.
        /// </summary>
        public static string Row {
            get {
                return ResourceManager.GetString("Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نتیجه جستجو.
        /// </summary>
        public static string SearchResult {
            get {
                return ResourceManager.GetString("SearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز و امنیت.
        /// </summary>
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحوه ارسال مدارک.
        /// </summary>
        public static string SelectAddress {
            get {
                return ResourceManager.GetString("SelectAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا درگاه مورد نظر را انتخاب نمایید.
        /// </summary>
        public static string SelectGateway {
            get {
                return ResourceManager.GetString("SelectGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعیین اقلام سفارش.
        /// </summary>
        public static string SelectOrderItem {
            get {
                return ResourceManager.GetString("SelectOrderItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هدف از ثبت سفارش خود را انتخاب نمایید..
        /// </summary>
        public static string SelectOrderPurposeTile {
            get {
                return ResourceManager.GetString("SelectOrderPurposeTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} عزیز ، آدرس دفتر ترجمه رسمی آنلاین به شرح زیر میباشد:
        ///{1}
        ///لوکیشن :
        ///https://goo.gl/maps/nWfrH3Kccqm.
        /// </summary>
        public static string SendCompanyAddressToUser {
            get {
                return ResourceManager.GetString("SendCompanyAddressToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعمال کد تخفیف.
        /// </summary>
        public static string SendDiscountCode {
            get {
                return ResourceManager.GetString("SendDiscountCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال کد تخفیف.
        /// </summary>
        public static string SendDiscountCodeTitle {
            get {
                return ResourceManager.GetString("SendDiscountCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد تخفیف دارم.
        /// </summary>
        public static string SendDiscountText {
            get {
                return ResourceManager.GetString("SendDiscountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن ارسالی به ایمیل {0} :.
        /// </summary>
        public static string SendEmailText {
            get {
                return ResourceManager.GetString("SendEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال پیام به کاربران.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی، کد تخفیف شما {0} می باشد..
        /// </summary>
        public static string SendMessageDescription {
            get {
                return ResourceManager.GetString("SendMessageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در زیر امکان ارسال پیامک و یا پست الکترونیکی به شماره موبایل و یا ایمیل مورد نظر وجود دارد.
        /// </summary>
        public static string SendMessageToUserDescription {
            get {
                return ResourceManager.GetString("SendMessageToUserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن ارسالی به شماره {0} :.
        /// </summary>
        public static string SendSmsText {
            get {
                return ResourceManager.GetString("SendSmsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در این صفحه امکان مدیریت تنظیمات کلی سیستم وجود دارد.
        /// </summary>
        public static string SettingDescription {
            get {
                return ResourceManager.GetString("SettingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت تنظیمات.
        /// </summary>
        public static string SettingManagment {
            get {
                return ResourceManager.GetString("SettingManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج.
        /// </summary>
        public static string Signout {
            get {
                return ResourceManager.GetString("Signout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عضویت.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیامکی حاوی کد تایید به شماره شما ارسال شد، لطفا آن را وارد نمایید.
        /// </summary>
        public static string SignUpSuccess {
            get {
                return ResourceManager.GetString("SignUpSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رسمی آنلاین.
        /// </summary>
        public static string SiteName {
            get {
                return ResourceManager.GetString("SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موفق.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات سیستم.
        /// </summary>
        public static string SystemSetting {
            get {
                return ResourceManager.GetString("SystemSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جدول.
        /// </summary>
        public static string Tabel {
            get {
                return ResourceManager.GetString("Tabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن ثابت.
        /// </summary>
        public static string Tel {
            get {
                return ResourceManager.GetString("Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گذرواژه با تکرار آن مطابقت ندارد.
        /// </summary>
        public static string ThePasswordDoesNotMatchIt {
            get {
                return ResourceManager.GetString("ThePasswordDoesNotMatchIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ آیتمی وجود ندارد.
        /// </summary>
        public static string ThereIsNoRecord {
            get {
                return ResourceManager.GetString("ThereIsNoRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای کاربر هیچ نقشی تعریف نشده است.
        /// </summary>
        public static string ThereIsNoView {
            get {
                return ResourceManager.GetString("ThereIsNoView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هزینه نسخه های اضافی.
        /// </summary>
        public static string TotalCopyPrice {
            get {
                return ResourceManager.GetString("TotalCopyPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع سفارشات.
        /// </summary>
        public static string TotalOrder {
            get {
                return ResourceManager.GetString("TotalOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جمع کل پرداختی.
        /// </summary>
        public static string TotalPayedPrice {
            get {
                return ResourceManager.GetString("TotalPayedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت کل.
        /// </summary>
        public static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهت جستجوی پیشرفته ضربه بزنید....
        /// </summary>
        public static string TouchForSearch {
            get {
                return ResourceManager.GetString("TouchForSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد رهگیری.
        /// </summary>
        public static string TrackingId {
            get {
                return ResourceManager.GetString("TrackingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یکی از کاربران رسمی آنلاین با نام ‘{0}’ سفارش خود را به شرح زیر پرداخت نموده است :
        ///شماره سفارش : {1}
        ///درگاه بانکی : {2}
        ///مبلغ پرداختی : {3}
        ///کد رهگیری : {4}
        ///#واریز_آنلاین.
        /// </summary>
        public static string Transaction_Add_Bot {
            get {
                return ResourceManager.GetString("Transaction_Add_Bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} عزیز، سفارش شماره {1} با موفقیت پرداخت گردید..
        /// </summary>
        public static string Transaction_Add_Sms {
            get {
                return ResourceManager.GetString("Transaction_Add_Sms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراکنش مورد نظر با خطا مواجه شده است.
        /// </summary>
        public static string TransactionFailed {
            get {
                return ResourceManager.GetString("TransactionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراکنش مورد نظر با موفقیت انجام پذیرفت.
        /// </summary>
        public static string TransactionSuccess {
            get {
                return ResourceManager.GetString("TransactionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واحد.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نامشخص.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نا موفق.
        /// </summary>
        public static string UnSuccess {
            get {
                return ResourceManager.GetString("UnSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات شخصی شما با موفقیت ثبت شد.
        /// </summary>
        public static string UpdatePersonelInfoSucessMsg {
            get {
                return ResourceManager.GetString("UpdatePersonelInfoSucessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بارگذاری فایل های مدارک.
        /// </summary>
        public static string UploadFiles {
            get {
                return ResourceManager.GetString("UploadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با توجه به حساسیت درج صحیح اسامی در مدارک رسمی تاکید می شود که تصویر مطلوب با اسکن پاسپورت خود را در این قسمت آپلود نمایید و یا اسپل صحیح اسامی موجود در مدارک سفارش خود را در قسمت مربوطه تایپ نمایید ..
        /// </summary>
        public static string UploadIdentityFilesText {
            get {
                return ResourceManager.GetString("UploadIdentityFilesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to `کاربر گرامی، لطفا جهت تسریع فرآیند ترجمه سفارش خود، از اسکن یا تصویر با کیفیت برای آپلود استفاده نمایید.
        /// </summary>
        public static string UploadOrderFilesText {
            get {
                return ResourceManager.GetString("UploadOrderFilesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استفاده از کد تخفیف.
        /// </summary>
        public static string UseDiscount {
            get {
                return ResourceManager.GetString("UseDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات حساب کاربری.
        /// </summary>
        public static string UserAccountInformation {
            get {
                return ResourceManager.GetString("UserAccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت کاربران.
        /// </summary>
        public static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت کاربران این نقش.
        /// </summary>
        public static string UserManagmentInRole {
            get {
                return ResourceManager.GetString("UserManagmentInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری اشتباه است.
        /// </summary>
        public static string UsernameIsWrong {
            get {
                return ResourceManager.GetString("UsernameIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری وارد نشده است.
        /// </summary>
        public static string UserNameNotEnter {
            get {
                return ResourceManager.GetString("UserNameNotEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر مورد نظر یافت نشد.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آمارهای معرف.
        /// </summary>
        public static string UserReferral {
            get {
                return ResourceManager.GetString("UserReferral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربران.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجوی کاربران.
        /// </summary>
        public static string UserSearch {
            get {
                return ResourceManager.GetString("UserSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعتبار سنجی ناموفق بود، لطفا دوباره سعی نمایید.
        /// </summary>
        public static string ValidationFailed {
            get {
                return ResourceManager.GetString("ValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعتبار از.
        /// </summary>
        public static string ValidFrom {
            get {
                return ResourceManager.GetString("ValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعتبار تا.
        /// </summary>
        public static string ValidTo {
            get {
                return ResourceManager.GetString("ValidTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار/درصد.
        /// </summary>
        public static string ValuePercent {
            get {
                return ResourceManager.GetString("ValuePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا برای تایید عضویت کد {0} را در سایت رسمی‌آنلاین وارد کنید..
        /// </summary>
        public static string VerificationCodeSms {
            get {
                return ResourceManager.GetString("VerificationCodeSms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت صفحات.
        /// </summary>
        public static string ViewManagement {
            get {
                return ResourceManager.GetString("ViewManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت صفحات این نقش.
        /// </summary>
        public static string ViewManagmentInRole {
            get {
                return ResourceManager.GetString("ViewManagmentInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجوی صفحات(ویوها).
        /// </summary>
        public static string ViewSearch {
            get {
                return ResourceManager.GetString("ViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در انتظار پرداخت.
        /// </summary>
        public static string WaitForPayment {
            get {
                return ResourceManager.GetString("WaitForPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هشدار.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بله.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
